<a href="https://colab.research.google.com/github/essensha/cs2-anti-cheat-ml-research/blob/main/Counter_Strike_2_Cheat_Detection_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Load your CSV from the srv folder
events = pd.read_csv("/srv/Counter Strike cheating.csv")

# Confirm it loaded
print("Dataset shape:", events.shape)
print("\nColumns:")
print(events.columns.tolist())

# Preview the first five rows
display(events.head())

Dataset shape: (6364, 1)

Columns:
['cs2_match_0_events2']

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           cs2_match_0_events2
cs2_match_0_events NaN  NaN   NaN           NaN              NaN              NaN           NaN           NaN            NaN NaN     NaN                 NaN                 NaN                   NaN      NaN        NaN                NaN       NaN        NaN       NaN      NaN      NaN    NaN         NaN        NaN      NaN    NaN      NaN    NaN   NaN       NaN        NaN  NaN  NaN      NaN      NaN     NaN              NaN      NaN     NaN     NaN       NaN        NaN         NaN      NaN      NaN          NaN    NaN     NaN      NaN    NaN  NaN  NaN       NaN          NaN   NaN     NaN            NaN    NaN               NaN           NaN     NaN  NaN NaN                 NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       NaN                 NaN
event_type         tick armor assistedflash assister_steamid attacker_steamid attackerblind attackerinair blind_duration bot canzoom damage_dir_x        damage_dir_y        damage_dir_z          defindex disconnect distance           dmg_armor dmg_health dominated entindex entityid haskit hassilencer hastracers headshot health hitgroup in_air isbot ispainted issilenced item name no_scope noreplay noscope num_penetrations num_wins oldteam otherid othertype penetrated rank_change rank_new rank_old rank_type_id reason revenge silenced silent site team thrusmoke user_steamid value version victim_steamid weapon weapon_fauxitemid weapon_itemid weptype wipe x   y                     z
bullet_damage      1944 NaN   NaN           NaN              Player_1         NaN           NaN           NaN            NaN NaN     0.9540976285934450  0.29941001534462000 0.007158827036619190  NaN      NaN        1642.4642333984400 NaN       NaN        NaN       NaN      NaN      NaN    NaN         NaN        NaN      NaN    NaN      FALSE  NaN   NaN       NaN        NaN  NaN  FALSE    NaN      NaN     0                NaN      NaN     NaN     NaN       NaN        NaN         NaN      NaN      NaN          NaN    NaN     NaN      NaN    NaN  NaN  NaN       NaN          NaN   NaN     Player_9       NaN    NaN               NaN           NaN     NaN  NaN NaN                 NaN
                   2006 NaN   NaN           NaN              Player_9         NaN           NaN           NaN            NaN NaN     -0.9558275938034060 -0.2936347723007200 -0.013127793557941900 NaN      NaN        17.690616607666000 NaN       NaN        NaN       NaN      NaN      NaN    NaN         NaN        NaN      NaN    NaN      FALSE  NaN   NaN       NaN        NaN  NaN  FALSE    NaN      NaN     1                NaN      NaN     NaN     NaN       NaN        NaN         NaN      NaN      NaN          NaN    NaN     NaN      NaN    NaN  NaN  NaN       NaN          NaN   NaN     Player_1       NaN    NaN               NaN           NaN     NaN  NaN NaN                 NaN

In [ ]:
import pandas as pd

# Skip the extra title row added by Numbers
df = pd.read_csv(
    "/srv/Counter Strike cheating.csv",
    skiprows=2
)

print("Dataset shape:", df.shape)
print("Columns:", df.columns.tolist()[:10])

display(df.head())

Dataset shape: (6362, 66)
Columns: ['cs2_match_0_events', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']

,cs2_match_0_events,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,event_type,tick,armor,assistedflash,assister_steamid,attacker_steamid,attackerblind,attackerinair,blind_duration,bot,...,version,victim_steamid,weapon,weapon_fauxitemid,weapon_itemid,weptype,wipe,x,y,z
1,bullet_damage,1944,NaN,NaN,NaN,Player_1,NaN,NaN,NaN,NaN,...,NaN,Player_9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,bullet_damage,2006,NaN,NaN,NaN,Player_9,NaN,NaN,NaN,NaN,...,NaN,Player_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bullet_damage,2503,NaN,NaN,NaN,Player_2,NaN,NaN,NaN,NaN,...,NaN,Player_9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bullet_damage,2542,NaN,NaN,NaN,Player_4,NaN,NaN,NaN,NaN,...,NaN,Player_8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd

# Inspect the raw CSV structure
preview = pd.read_csv(
    "/srv/Counter Strike cheating.csv",
    header=None,
    nrows=6
)

display(preview.iloc[:, :10])

ParserError: Error tokenizing data. C error: Expected 1 fields in line 2, saw 66

In [ ]:
import pandas as pd

df = pd.read_csv(
    "/srv/Counter Strike cheating.csv",
    skiprows=1
)

print("Dataset shape:", df.shape)
print("\nFirst 10 columns:")
print(df.columns.tolist()[:10])

display(df.head())

Dataset shape: (6363, 66)

First 10 columns:
['cs2_match_0_events', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']

,cs2_match_0_events,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,cs2_match_0_events,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,event_type,tick,armor,assistedflash,assister_steamid,attacker_steamid,attackerblind,attackerinair,blind_duration,bot,...,version,victim_steamid,weapon,weapon_fauxitemid,weapon_itemid,weptype,wipe,x,y,z
2,bullet_damage,1944,NaN,NaN,NaN,Player_1,NaN,NaN,NaN,NaN,...,NaN,Player_9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bullet_damage,2006,NaN,NaN,NaN,Player_9,NaN,NaN,NaN,NaN,...,NaN,Player_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bullet_damage,2503,NaN,NaN,NaN,Player_2,NaN,NaN,NaN,NaN,...,NaN,Player_9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd

df = pd.read_csv(
    "/srv/Counter Strike cheating.csv",
    skiprows=3
)

print("Dataset shape:", df.shape)
print("\nFirst 10 columns:")
print(df.columns.tolist()[:10])

display(df.head())

Dataset shape: (6361, 66)

First 10 columns:
['event_type', 'tick', 'armor', 'assistedflash', 'assister_steamid', 'attacker_steamid', 'attackerblind', 'attackerinair', 'blind_duration', 'bot']

,event_type,tick,armor,assistedflash,assister_steamid,attacker_steamid,attackerblind,attackerinair,blind_duration,bot,...,version,victim_steamid,weapon,weapon_fauxitemid,weapon_itemid,weptype,wipe,x,y,z
0,bullet_damage,1944,NaN,NaN,NaN,Player_1,NaN,NaN,NaN,NaN,...,NaN,Player_9,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
1,bullet_damage,2006,NaN,NaN,NaN,Player_9,NaN,NaN,NaN,NaN,...,NaN,Player_1,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
2,bullet_damage,2503,NaN,NaN,NaN,Player_2,NaN,NaN,NaN,NaN,...,NaN,Player_9,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
3,bullet_damage,2542,NaN,NaN,NaN,Player_4,NaN,NaN,NaN,NaN,...,NaN,Player_8,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
4,bullet_damage,2640,NaN,NaN,NaN,Player_2,NaN,NaN,NaN,NaN,...,NaN,Player_10,NaN,,NaN,NaN,NaN,NaN,NaN,NaN

Explore gameplay event distributions

In [ ]:
# Count the frequency of each gameplay event type
event_counts = (
    df["event_type"]
    .value_counts()
    .reset_index()
)

event_counts.columns = ["event_type", "count"]

display(event_counts)

print("Total events:", event_counts["count"].sum())

                        event_type  count
0                       item_equip   2214
1                      weapon_fire   1008
2                  player_footstep    641
3                      player_jump    589
4                      item_pickup    491
5                      player_hurt    330
6                    bullet_damage    209
7                      weapon_zoom    142
8                     player_spawn    140
9                     player_death     84
10                     server_cvar     45
11             cs_round_start_beep     42
12                    player_blind     42
13                   weapon_reload     35
14                     bomb_pickup     29
15                     other_death     28
16                    bomb_dropped     27
17          round_officially_ended     26
18            weapon_fire_on_empty     22
19              flashbang_detonate     21
20           smokegrenade_detonate     18
21            smokegrenade_expired     17
22                   buytime_ended     15
23                round_freeze_end     14
24             cs_round_final_beep     14
25                  round_prestart     14
26                  cs_pre_restart     14
27                 round_poststart     14
28               inferno_startburn     11
29                  inferno_expire     11
30                     rank_update     10
31                     player_team     10
32               player_disconnect     10
33              hegrenade_detonate      9
34                  player_connect      2
35             player_connect_full      2
36      round_announce_match_point      1
37                 bomb_beginplant      1
38                 begin_new_match      1
39                    bomb_planted      1
40      round_announce_match_start      1
41                hltv_versioninfo      1
42                bomb_begindefuse      1
43                   bomb_exploded      1
44  round_announce_last_round_half      1
45              cs_win_panel_match      1
46              announce_phase_end      1

Total events: 6361

Let's examine whether labeled cheaters actually have fewer footsteps.

In [ ]:
footsteps = df[df["event_type"] == "player_footstep"]

print("Available player columns:")
print([c for c in footsteps.columns
       if "steamid" in c or "userid" in c])

display(footsteps.head(3))

Available player columns:
['assister_steamid', 'attacker_steamid', 'user_steamid', 'victim_steamid']

,event_type,tick,armor,assistedflash,assister_steamid,attacker_steamid,attackerblind,attackerinair,blind_duration,bot,...,version,victim_steamid,weapon,weapon_fauxitemid,weapon_itemid,weptype,wipe,x,y,z
378,player_footstep,1481,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
379,player_footstep,1528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
380,player_footstep,1543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Verify the player identifier is populated
print("Missing player IDs:",
      footsteps["user_steamid"].isna().sum())

# Count footsteps per player
footstep_counts = (
    footsteps.groupby("user_steamid")
    .size()
    .reset_index(name="footstep_count")
)

# Add known labels from this match
footstep_counts["cheater"] = (
    footstep_counts["user_steamid"]
    .isin(["Player_3", "Player_4"])
)

display(
    footstep_counts.sort_values(
        "footstep_count", ascending=False
    )
)

Missing player IDs: 0

  user_steamid  footstep_count  cheater
0     Player_1             193    False
4     Player_4              90     True
9     Player_9              79    False
2     Player_2              77    False
6     Player_6              56    False
3     Player_3              43     True
8     Player_8              39    False
1    Player_10              27    False
7     Player_7              26    False
5     Player_5              11    False

In [ ]:
# Count player spawns
spawns = df[df["event_type"] == "player_spawn"]

spawn_counts = (
    spawns.groupby("user_steamid")
    .size()
    .reset_index(name="spawn_count")
)

# Combine footsteps and spawns
player_features = footstep_counts.merge(
    spawn_counts,
    on="user_steamid",
    how="left"
)

player_features["footsteps_per_spawn"] = (
    player_features["footstep_count"] /
    player_features["spawn_count"]
)

display(
    player_features.sort_values(
        "footsteps_per_spawn",
        ascending=False
    )
)

  user_steamid  footstep_count  cheater  spawn_count  footsteps_per_spawn
0     Player_1             193    False           14            13.785714
4     Player_4              90     True           14             6.428571
9     Player_9              79    False           14             5.642857
2     Player_2              77    False           14             5.500000
6     Player_6              56    False           13             4.307692
3     Player_3              43     True           14             3.071429
8     Player_8              39    False           14             2.785714
7     Player_7              26    False           14             1.857143
1    Player_10              27    False           15             1.800000
5     Player_5              11    False           14             0.785714

In [ ]:
# Identify potential reaction-time and aiming fields
keywords = [
    "time", "tick", "aim", "angle",
    "view", "target", "position",
    "visible", "reaction"
]

candidate_columns = [
    col for col in df.columns
    if any(word in col.lower() for word in keywords)
]

print("Potentially relevant columns:")
print(candidate_columns)

Potentially relevant columns:
['tick']

In [ ]:
shots = df[df["event_type"] == "weapon_fire"].copy()

print("Total weapon-fire events:", len(shots))
print("Missing player IDs:", shots["user_steamid"].isna().sum())

display(
    shots[["user_steamid", "tick", "weapon"]].head(10)
)

Total weapon-fire events: 1008
Missing player IDs: 0

     user_steamid  tick               weapon
2983    Player_10  1552  weapon_smokegrenade
2984     Player_1  1701         weapon_knife
2985     Player_2  1707         weapon_knife
2986     Player_2  1733         weapon_knife
2987     Player_6  1740       weapon_knife_t
2988     Player_2  1759         weapon_knife
2989     Player_8  1759       weapon_knife_t
2990     Player_1  1944  weapon_usp_silencer
2991     Player_9  1945         weapon_glock
2992     Player_9  1962         weapon_glock

First few observations include knives and a smoke grenade. We should exclude those before analyzing gunfire timing

Calculate firing intervals

In [ ]:
# Exclude knives, grenades, and other non-gun weapons
guns = shots[
    ~shots["weapon"].str.contains(
        "knife|grenade|flashbang|molotov|incgrenade|decoy|c4|taser",
        case=False,
        na=True
    )
].copy()

# Sort shots by player, weapon, and timestamp
guns = guns.sort_values(
    ["user_steamid", "weapon", "tick"]
)

# Calculate time between consecutive shots
guns["shot_interval_ticks"] = (
    guns.groupby(["user_steamid", "weapon"])["tick"]
    .diff()
)

# Summarize intervals by player
interval_summary = (
    guns.groupby("user_steamid")["shot_interval_ticks"]
    .agg(["count", "mean", "std"])
    .reset_index()
)

interval_summary["cheater"] = (
    interval_summary["user_steamid"]
    .isin(["Player_3", "Player_4"])
)

display(interval_summary)

  user_steamid  count         mean           std  cheater
0     Player_1    191   478.397906   1767.107124    False
1    Player_10     86   147.953488    523.186119    False
2     Player_2     29  3239.344828  10089.324883    False
3     Player_3    100   850.680000   3671.219622     True
4     Player_4     63  1144.777778   4333.327967     True
5     Player_5     50   365.100000   1736.431930    False
6     Player_6     17  1707.588235   4096.418925    False
7     Player_7     69   199.652174    846.111344    False
8     Player_8     60   906.500000   4545.674739    False
9     Player_9    111   816.216216   4508.740982    False

In [ ]:
# Exclude knives, grenades, and other non-gun weapons
guns = shots[
    ~shots["weapon"].str.contains(
        "knife|grenade|flashbang|molotov|incgrenade|decoy|c4|taser",
        case=False,
        na=True
    )
].copy()

# Sort shots by player, weapon, and timestamp
guns = guns.sort_values(
    ["user_steamid", "weapon", "tick"]
)

# Calculate time between consecutive shots
guns["shot_interval_ticks"] = (
    guns.groupby(["user_steamid", "weapon"])["tick"]
    .diff()
)

# Summarize intervals by player
interval_summary = (
    guns.groupby("user_steamid")["shot_interval_ticks"]
    .agg(["count", "mean", "std"])
    .reset_index()
)

interval_summary["cheater"] = (
    interval_summary["user_steamid"]
    .isin(["Player_3", "Player_4"])
)

display(interval_summary)

  user_steamid  count         mean           std  cheater
0     Player_1    191   478.397906   1767.107124    False
1    Player_10     86   147.953488    523.186119    False
2     Player_2     29  3239.344828  10089.324883    False
3     Player_3    100   850.680000   3671.219622     True
4     Player_4     63  1144.777778   4333.327967     True
5     Player_5     50   365.100000   1736.431930    False
6     Player_6     17  1707.588235   4096.418925    False
7     Player_7     69   199.652174    846.111344    False
8     Player_8     60   906.500000   4545.674739    False
9     Player_9    111   816.216216   4508.740982    False

Both labeled cheaters have relatively high variability. Some legitimate players have much lower variability.

But there's an important methodological problem: This calculation includes long gaps between firefights and rounds. These gaps inflate standard deviations, so we haven't actually measured firing consistency within shooting bursts.

In [ ]:
# Explore short intervals between shots
short_intervals = guns[
    guns["shot_interval_ticks"].between(1, 100)
].copy()

summary = (
    short_intervals.groupby("user_steamid")["shot_interval_ticks"]
    .agg(["count", "mean", "std"])
    .reset_index()
)

summary["cheater"] = summary["user_steamid"].isin(
    ["Player_3", "Player_4"]
)

display(summary)

  user_steamid  count       mean        std  cheater
0     Player_1    161  15.689441  16.688782    False
1    Player_10     72  14.333333  14.262133    False
2     Player_2     11  37.636364  16.113800    False
3     Player_3     68  33.691176  26.053480     True
4     Player_4     39  10.820513  14.029802     True
5     Player_5     47  14.425532  18.444682    False
6     Player_6      8  34.000000  27.318230    False
7     Player_7     57  17.877193  13.758206    False
8     Player_8     53  19.207547  11.432677    False
9     Player_9     91  17.263736  18.496147    False

In [ ]:
weapon_usage = pd.crosstab(
    guns["user_steamid"],
    guns["weapon"]
)

display(weapon_usage)

weapon,weapon_ak47,weapon_awp,weapon_cz75a,weapon_deagle,weapon_elite,weapon_galilar,weapon_glock,weapon_hkp2000,weapon_m4a1_silencer,weapon_mp9,weapon_nova,weapon_p250,weapon_revolver,weapon_scar20,weapon_ssg08,weapon_tec9,weapon_usp_silencer,weapon_xm1014
user_steamid,,,,,,,,,,,,,,,,,,
Player_1,14,0,0,4,0,0,0,0,82,31,0,9,3,0,0,0,55,0
Player_10,0,0,0,3,60,8,1,0,0,0,0,0,7,0,12,0,0,2
Player_2,0,10,0,12,0,0,0,10,0,0,0,0,0,0,0,0,0,0
Player_3,0,0,0,15,0,0,0,0,20,0,0,0,13,12,28,12,7,0
Player_4,0,14,15,1,0,0,0,0,35,0,0,0,0,0,0,0,3,0
Player_5,0,0,0,2,0,0,0,0,9,37,6,0,0,0,0,0,0,0
Player_6,2,0,0,13,0,0,0,0,0,0,0,1,0,0,5,0,0,0
Player_7,13,0,0,1,0,0,7,0,0,0,0,0,0,0,7,0,46,0
Player_8,14,0,0,11,0,0,2,0,0,0,0,0,0,0,0,0,37,0
Player_9,68,1,0,22,0,0,12,0,0,0,8,0,0,0,0,0,3,4

Both players use the M4A1-S, making it a useful starting point for a controlled comparison.

In [ ]:
# Restrict analysis to M4A1-S
m4 = guns[
    guns["weapon"] == "weapon_m4a1_silencer"
].copy()

# Calculate intervals between M4A1-S shots
m4 = m4.sort_values(["user_steamid", "tick"])

m4["interval"] = (
    m4.groupby("user_steamid")["tick"].diff()
)

# Focus on short intervals
m4_short = m4[m4["interval"].between(1, 100)]

results = (
    m4_short.groupby("user_steamid")["interval"]
    .agg(["count", "mean", "std"])
    .reset_index()
)

results["cheater"] = results["user_steamid"].isin(
    ["Player_3", "Player_4"]
)

display(results)

  user_steamid  count       mean        std  cheater
0     Player_1     75  12.413333  10.815521    False
1     Player_3     19  15.000000  21.137118     True
2     Player_4     29   9.275862  15.341113     True
3     Player_5      7  28.428571   5.255383    False

Inspect round-boundary timestamps

In [ ]:
round_events = df[
    df["event_type"].isin([
        "round_prestart",
        "round_freeze_end",
        "round_officially_ended"
    ])
]

display(
    round_events[
        ["event_type", "tick"]
    ].sort_values("tick").head(20)
)

                  event_type   tick
2582          round_prestart     65
6346        round_freeze_end   1441
6321  round_officially_ended   3944
2583          round_prestart   3944
6320  round_officially_ended   3944
6347        round_freeze_end   4904
2584          round_prestart   7352
6322  round_officially_ended   7352
6323  round_officially_ended   7352
6348        round_freeze_end  10784
6325  round_officially_ended  15742
2585          round_prestart  15742
6324  round_officially_ended  15742
6349        round_freeze_end  16702
6327  round_officially_ended  19304
6326  round_officially_ended  19304
2586          round_prestart  19304
6350        round_freeze_end  20264
6329  round_officially_ended  24037
6328  round_officially_ended  24037

Assign rounds to weapon-fire events

In [ ]:
import pandas as pd

# Get unique round starting ticks
round_starts = (
    df.loc[
        df["event_type"] == "round_prestart",
        ["tick"]
    ]
    .drop_duplicates()
    .sort_values("tick")
    .reset_index(drop=True)
)

round_starts["round_id"] = range(
    1, len(round_starts) + 1
)

# Assign each gunshot to the most recent round start
guns_by_round = pd.merge_asof(
    guns.sort_values("tick").copy(),
    round_starts,
    on="tick",
    direction="backward"
)

print("Rounds identified:", len(round_starts))
print("Shots without a round:", guns_by_round["round_id"].isna().sum())

display(
    guns_by_round[
        ["user_steamid", "weapon", "tick", "round_id"]
    ].head(10)
)

Rounds identified: 14
Shots without a round: 0

  user_steamid               weapon  tick  round_id
0     Player_1  weapon_usp_silencer  1944         1
1     Player_9         weapon_glock  1945         1
2     Player_9         weapon_glock  1962         1
3     Player_9         weapon_glock  1977         1
4     Player_1  weapon_usp_silencer  1979         1
5     Player_9         weapon_glock  1992         1
6     Player_1  weapon_usp_silencer  1997         1
7     Player_9         weapon_glock  2006         1
8     Player_7         weapon_glock  2008         1
9     Player_1  weapon_usp_silencer  2010         1

first 10 gunshots have been assigned to Round 1, and their timestamps are in chronological order.

In [ ]:
# Select M4A1-S shots
m4_rounds = guns_by_round[
    guns_by_round["weapon"] == "weapon_m4a1_silencer"
].copy()

# Calculate firing intervals within each round
m4_rounds = m4_rounds.sort_values(
    ["user_steamid", "round_id", "tick"]
)

m4_rounds["interval"] = (
    m4_rounds.groupby(
        ["user_steamid", "round_id"]
    )["tick"].diff()
)

# Keep short intervals for exploratory analysis
m4_short = m4_rounds[
    m4_rounds["interval"].between(1, 100)
]

# Summarize by player
results = (
    m4_short.groupby("user_steamid")["interval"]
    .agg(["count", "mean", "std"])
    .reset_index()
)

results["cheater"] = results["user_steamid"].isin(
    ["Player_3", "Player_4"]
)

display(results)

  user_steamid  count       mean        std  cheater
0     Player_1     75  12.413333  10.815521    False
1     Player_3     19  15.000000  21.137118     True
2     Player_4     29   9.275862  15.341113     True
3     Player_5      7  28.428571   5.255383    False

Before moving to another feature, let's check whether the original short intervals ever crossed round boundaries

In [ ]:
# Original M4A1-S shot sequence
check = guns[
    guns["weapon"] == "weapon_m4a1_silencer"
].copy()

# Assign round IDs
check = pd.merge_asof(
    check.sort_values("tick"),
    round_starts,
    on="tick",
    direction="backward"
)

check = check.sort_values(["user_steamid", "tick"])

# Identify previous shot and previous round
check["previous_tick"] = (
    check.groupby("user_steamid")["tick"].shift()
)

check["previous_round"] = (
    check.groupby("user_steamid")["round_id"].shift()
)

check["interval"] = check["tick"] - check["previous_tick"]

# Count short intervals crossing rounds
cross_round = check[
    check["interval"].between(1, 100)
    & (check["round_id"] != check["previous_round"])
]

print("Short intervals crossing rounds:", len(cross_round))

Short intervals crossing rounds: 0

Short intervals crossing rounds: 0 confirms that none of the M4A1-S firing intervals retained by our 100-tick filter crossed a round boundary.

Investigate damage-related features

Our next research question is whether labeled cheaters demonstrate unusual damage patterns relative to legitimate players

In [ ]:
# Examine bullet-damage event structure
damage = df[
    df["event_type"] == "bullet_damage"
].copy()

# Identify columns with recorded values
available = damage.columns[
    damage.notna().any()
].tolist()

print("Bullet-damage events:", len(damage))
print("\nAvailable fields:")
print(available)

display(damage[available].head())

Bullet-damage events: 209

Available fields:
['event_type', 'tick', 'attacker_steamid', 'damage_dir_x', 'damage_dir_y', 'damage_dir_z', 'distance', 'in_air', 'no_scope', 'num_penetrations', 'victim_steamid', 'weapon_fauxitemid']

,event_type,tick,attacker_steamid,damage_dir_x,damage_dir_y,damage_dir_z,distance,in_air,no_scope,num_penetrations,victim_steamid,weapon_fauxitemid
0,bullet_damage,1944,Player_1,0.954098,0.299410,0.007159,1642.464233,False,False,0.0,Player_9,
1,bullet_damage,2006,Player_9,-0.955828,-0.293635,-0.013128,17.690617,False,False,1.0,Player_1,
2,bullet_damage,2503,Player_2,-0.101817,0.983765,-0.147784,694.732239,False,False,0.0,Player_9,
3,bullet_damage,2542,Player_4,0.845778,-0.533501,-0.006035,551.182251,False,False,0.0,Player_8,
4,bullet_damage,2640,Player_2,-0.168328,0.985715,-0.005682,1647.887695,False,False,0.0,Player_10,

In [ ]:
# Summarize damage-event distances by attacker
distance_summary = (
    damage.groupby("attacker_steamid")["distance"]
    .agg(["count", "mean", "median", "max"])
    .reset_index()
)

distance_summary["cheater"] = (
    distance_summary["attacker_steamid"]
    .isin(["Player_3", "Player_4"])
)

display(
    distance_summary.sort_values(
        "mean",
        ascending=False
    )
)

  attacker_steamid  count        mean      median          max  cheater
1        Player_10     14  819.973942  515.831146  1698.478271    False
4         Player_4     33  743.479187  638.277710  1207.440186     True
3         Player_3     43  714.937813  737.723389  1649.987915     True
2         Player_2      7  659.301688  694.732239  1647.887695    False
0         Player_1     31  652.275197  707.870361  1642.464233    False
8         Player_8      5  600.878650  396.482727  1363.093994    False
5         Player_5     24  534.559324  630.149078  1179.852417    False
9         Player_9     45  504.353779  588.386353  1702.524780    False
6         Player_6      3  439.236280  591.322571   646.554138    False
7         Player_7      4  414.727186  266.630228  1074.599243    False

In [ ]:
# Count recorded gunfire events per player
shots_per_player = (
    guns.groupby("user_steamid")
    .size()
    .rename("gunfire_events")
)

# Count bullet-damage events per attacker
damage_per_player = (
    damage.groupby("attacker_steamid")
    .size()
    .rename("damage_events")
)

# Combine counts
combat = pd.concat(
    [shots_per_player, damage_per_player],
    axis=1
).fillna(0)

combat["damage_events_per_fire"] = (
    combat["damage_events"] /
    combat["gunfire_events"].replace(0, float("nan"))
)

combat["cheater"] = combat.index.isin(
    ["Player_3", "Player_4"]
)

display(
    combat.sort_values(
        "damage_events_per_fire",
        ascending=False
    )
)

           gunfire_events  damage_events  damage_events_per_fire  cheater
Player_4               68             33                0.485294     True
Player_5               54             24                0.444444    False
Player_3              107             43                0.401869     True
Player_9              118             45                0.381356    False
Player_2               32              7                0.218750    False
Player_1              198             31                0.156566    False
Player_10              93             14                0.150538    False
Player_6               21              3                0.142857    False
Player_8               64              5                0.078125    False
Player_7               74              4                0.054054    False

Player_3 and Player_4 have relatively high damage-event ratios. But Player_5: a legitimate player with a ratio of 0.444, higher than Player_3.

Test the false-positive tradeoff

In [ ]:
# Flag players with high damage-event ratios
combat["flagged"] = combat["damage_events_per_fire"] >= 0.40

# Compare flags against known labels
print(pd.crosstab(
    combat["cheater"],
    combat["flagged"],
    rownames=["Actual cheater"],
    colnames=["Flagged suspicious"]
))

Flagged suspicious  False  True
Actual cheater
False                   7      1
True                    0      2

Precision
66.7%
2 of 3 flags correct

Recall
100%
2 of 2 cheaters detected

False-positive rate
12.5%
1 of 8 legitimate players flagged

F1 score
80%
Precision–recall balance

###Build our player-level feature dataset

Before training a model, we need one row per player, with all three features and the known cheating labels

In [ ]:
# Start with our combat feature table
features = combat[
    ["damage_events_per_fire", "cheater"]
].copy()

# Add footsteps per spawn
footstep_feature = (
    player_features
    .set_index("user_steamid")["footsteps_per_spawn"]
)

features = features.join(footstep_feature)

# Add M4A1-S firing interval variability
firing_feature = (
    results
    .set_index("user_steamid")["std"]
    .rename("m4_firing_std")
)

features = features.join(firing_feature)

print("Dataset shape:", features.shape)
display(features)
print("\nMissing values:")
print(features.isna().sum())

Dataset shape: (10, 4)

           damage_events_per_fire  cheater  footsteps_per_spawn  m4_firing_std
Player_1                 0.156566    False            13.785714      10.815521
Player_10                0.150538    False             1.800000            NaN
Player_2                 0.218750    False             5.500000            NaN
Player_3                 0.401869     True             3.071429      21.137118
Player_4                 0.485294     True             6.428571      15.341113
Player_5                 0.444444    False             0.785714       5.255383
Player_6                 0.142857    False             4.307692            NaN
Player_7                 0.054054    False             1.857143            NaN
Player_8                 0.078125    False             2.785714            NaN
Player_9                 0.381356    False             5.642857            NaN

Missing values:
damage_events_per_fire    0
cheater                   0
footsteps_per_spawn       0
m4_firing_std             6
dtype: int64

 Create a model-ready baseline

In [ ]:
# Select complete features for the initial baseline
baseline_features = features[
    ["damage_events_per_fire", "footsteps_per_spawn", "cheater"]
].copy()

# Separate predictors from labels
X = baseline_features.drop(columns="cheater")
y = baseline_features["cheater"].astype(int)

print("Feature matrix:", X.shape)
print("Labels:", y.value_counts().to_dict())

print("\nMissing values:")
print(X.isna().sum())

display(X)

Feature matrix: (10, 2)
Labels: {0: 8, 1: 2}

Missing values:
damage_events_per_fire    0
footsteps_per_spawn       0
dtype: int64

           damage_events_per_fire  footsteps_per_spawn
Player_1                 0.156566            13.785714
Player_10                0.150538             1.800000
Player_2                 0.218750             5.500000
Player_3                 0.401869             3.071429
Player_4                 0.485294             6.428571
Player_5                 0.444444             0.785714
Player_6                 0.142857             4.307692
Player_7                 0.054054             1.857143
Player_8                 0.078125             2.785714
Player_9                 0.381356             5.642857

In [ ]:
import pandas as pd

labels = pd.read_csv(
    "/srv/cs2_match_0_cheater_labels.csv"
)

print("Shape:", labels.shape)
print("Columns:", labels.columns.tolist())

display(labels)

Shape: (10, 2)
Columns: ['steamid', 'is_labeled_cheater']

     steamid  is_labeled_cheater
0   Player_1                   0
1   Player_2                   0
2   Player_3                   1
3   Player_4                   1
4   Player_5                   0
5   Player_6                   0
6   Player_7                   0
7   Player_8                   0
8   Player_9                   0
9  Player_10                   0

In [ ]:
# Prepare the source labels
verified_labels = labels.set_index("steamid")[
    "is_labeled_cheater"
]

# Merge source labels with engineered features
model_df = X.join(verified_labels)

print("Dataset shape:", model_df.shape)
print("Missing labels:", model_df["is_labeled_cheater"].isna().sum())

display(model_df)

Dataset shape: (10, 3)
Missing labels: 0

           damage_events_per_fire  footsteps_per_spawn  is_labeled_cheater
Player_1                 0.156566            13.785714                   0
Player_10                0.150538             1.800000                   0
Player_2                 0.218750             5.500000                   0
Player_3                 0.401869             3.071429                   1
Player_4                 0.485294             6.428571                   1
Player_5                 0.444444             0.785714                   0
Player_6                 0.142857             4.307692                   0
Player_7                 0.054054             1.857143                   0
Player_8                 0.078125             2.785714                   0
Player_9                 0.381356             5.642857                   0

Save our baseline dataset

In [ ]:
# Preserve the source match identifier
match_0 = model_df.copy()

match_0["match_id"] = "match_0"

# Save the player-level dataset
output_path = "/srv/cs2_match_0_features.csv"

match_0.to_csv(
    output_path,
    index_label="player_id"
)

print("Saved:", output_path)
print("Shape:", match_0.shape)

display(match_0.head())

Saved: /srv/cs2_match_0_features.csv
Shape: (10, 4)

,damage_events_per_fire,footsteps_per_spawn,is_labeled_cheater,match_id
Player_1,0.156566,13.785714,0,match_0
Player_10,0.150538,1.800000,0,match_0
Player_2,0.218750,5.500000,0,match_0
Player_3,0.401869,3.071429,1,match_0
Player_4,0.485294,6.428571,1,match_0

In [ ]:
import os

for filename in ["match_0.json", "match_0.json"]:
    path = f"/srv/{filename}"

    print(
        filename,
        "Found!" if os.path.exists(path) else "Not found"
    )

match_0.json Not found
match_0.json Not found